name: "Debug Workflow"

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Show current directory
        run: pwd
      
      - name: List files in root
        run: ls -la
      
      - name: List files in app directory
        run: ls -la app/
      
      - name: Check if package-lock.json exists in app
        run: |
          if [ -f app/package-lock.json ]; then
            echo "package-lock.json exists in app directory"
            ls -la app/package-lock.json
          else
            echo "package-lock.json does not exist in app directory"
          fi
      
      - name: Check if package.json exists in app
        run: |
          if [ -f app/package.json ]; then
            echo "package.json exists in app directory"
            cat app/package.json
          else
            echo "package.json does not exist in app directory"
          fi
      
      - name: Try npm ci with explicit path
        run: |
          cd app
          npm ci 