name: "Develop Workflow - Enhanced Testing"

on:
  push:
    branches:
      - develop

jobs:
  enhanced-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd app
          npm ci
      
      - name: Run linting
        run: |
          cd app
          npm run lint
      
      - name: Run type checking
        run: |
          cd app
          npm run type-check
      
      - name: Run unit tests with coverage
        run: |
          cd app
          npm test -- --coverage
      
      - name: Build application
        run: |
          cd app
          npm run build
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: app/coverage/
          retention-days: 30
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: app/build/
          retention-days: 7
      
      - name: Security audit
        run: |
          cd app
          npm audit --audit-level moderate 