name: "PR Workflow - Build & Test"

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd app
          npm install
      
      - name: Run linting
        run: |
          cd app
          npm run lint
      
      - name: Run type checking
        run: |
          cd app
          npm run type-check
      
      - name: Run unit tests
        run: |
          cd app
          npm test
      
      - name: Build application
        run: |
          cd app
          npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: app/build/
          retention-days: 7
