name: "Push Workflow - Build & Test"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Copy package files to root for npm cache
        run: |
          cp app/package.json .
          cp app/package-lock.json .
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run type checking
        run: npm run type-check
      
      - name: Run unit tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: app/build/
          retention-days: 7
      
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r src/ deployment/
          cp package.json deployment/
          cp tsconfig.json deployment/
      
      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: app/deployment/
          retention-days: 30 