name: "Push Workflow - Build & Test"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: app

      - name: Run lint
        run: npm run lint
        working-directory: app

      - name: Run type-check
        run: npm run type-check
        working-directory: app

      - name: Run test
        run: npm test
        working-directory: app

      - name: Build
        run: npm run build
        working-directory: app
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: app/build/
          retention-days: 7
      
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r src/ deployment/
          cp package.json deployment/
          cp tsconfig.json deployment/
      
      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: app/deployment/
          retention-days: 30 